# Generated by Django 4.1.6 on 2023-02-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_place',
            field=models.IntegerField(default=None),
        ),
    ]
