# Generated by Django 4.1.2 on 2023-02-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_groupproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupProduct',
        ),
    ]
