# Generated by Django 4.1.2 on 2023-02-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_profile_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='serial',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
