# Generated by Django 4.1.2 on 2023-02-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_profile_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='email_or_username',
            field=models.TextField(default=''),
        ),
    ]
