# Generated by Django 4.1.2 on 2023-02-23 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0020_alter_profile_email_or_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inovie_rdp', models.IntegerField()),
                ('action_rdp', models.CharField(max_length=255)),
                ('ip_rdp', models.CharField(max_length=50)),
                ('username_rdp', models.CharField(max_length=100)),
                ('password_rdp', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
