# Generated by Django 4.1.2 on 2023-02-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rdp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdp',
            name='action_rdp',
        ),
    ]
