# Generated by Django 4.1.2 on 2023-03-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_rdp_action_rdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
