# Generated by Django 4.1.2 on 2023-03-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='paid_proxy',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True, default=''),
        ),
    ]
