# Generated by Django 4.1.7 on 2023-03-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_product_paid_proxy_alter_product_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dis', models.TextField()),
                ('image', models.ImageField(default='static/images/default.png', upload_to='static/images')),
            ],
        ),
    ]
