# Generated by Django 4.1.7 on 2023-03-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_freetool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freetool',
            name='image',
        ),
    ]
