# Generated by Django 4.1.7 on 2023-04-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_trending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trending',
            old_name='prodcut',
            new_name='product',
        ),
    ]
