# Generated by Django 4.1.7 on 2023-04-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_prodcut_trending_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='Tools', max_length=255),
        ),
    ]
