# Generated by Django 4.2 on 2023-04-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_groupproduct_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='product',
            field=models.ManyToManyField(default='', to='core.product'),
        ),
    ]
