# Generated by Django 4.2 on 2023-04-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_whoeditserial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whoeditserial',
            name='email_or_username',
        ),
        migrations.AddField(
            model_name='whoeditserial',
            name='user',
            field=models.CharField(default='', max_length=255),
        ),
    ]
