# Generated by Django 4.2 on 2023-05-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='service',
            field=models.CharField(choices=[('Guess', 'Guess'), ('Instagram', 'Instagram')], default='', max_length=250),
        ),
    ]
