# Generated by Django 4.2.1 on 2023-05-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_basket_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
