# Generated by Django 4.2.1 on 2023-05-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='item',
        ),
        migrations.AddField(
            model_name='basket',
            name='items',
            field=models.ManyToManyField(to='core.product'),
        ),
    ]
