# Generated by Django 4.2.1 on 2023-05-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_basket_item_basket_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.CharField(default='', max_length=255),
        ),
    ]
