# Generated by Django 4.2.1 on 2023-05-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_basket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='items',
        ),
        migrations.AddField(
            model_name='basket',
            name='items',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
