# Generated by Django 4.2.1 on 2023-05-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
