# Generated by Django 4.2.1 on 2023-05-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='type',
            field=models.CharField(default='', max_length=500),
        ),
    ]
