# Generated by Django 4.2.1 on 2023-06-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_bill_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
