# Generated by Django 4.2.1 on 2023-06-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_statusproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusProduct',
        ),
    ]
