# Generated by Django 4.2.1 on 2023-06-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_delete_statusproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
