# Generated by Django 4.2.1 on 2023-09-07 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_request_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('uses', models.IntegerField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 14, 24, 33, 960897)),
        ),
    ]
